site_name: Mis Documentos 

theme:
  name: material 
  language: es
  logo: assets/logo.png
  favicon: assets/favicon.png
  pallete:
    primary: 'teal'
    accent: 'blue'
  features:
    - header.autohide

repo_url: https://github.com/rguerrasev/rguerrasev.github.io

nav:
  - 'Inicio': 'index.md'
  - 'Sobre mi': 'aboutme.md'
  - 'Mi Entorno':
      - 'Herramientas' : 'herramientas.md'
      - 'Comandos Linux': 'comandos-linux.md'
  - 'Tutoriales':
      - 'Crear un sitio con MkDocs': 'tutoriales/crear-sitio-con-mkdocs.md'